- front-end/src/UI/Templates/MainSocial/index.tsx
ProfileHeader로 되어있는 export 함수 이름을 MainSocial로 올바르게
수정하였다.
> TL42-17 fix. MainSocial의 index.tsx에 대한 오타 수정

- front-end/src/Games/GameContext.ts
- front-end/src/Games/dto/constants/game.constants.ts
- 기존에는 게임 창에서 벗어날 때 아무런 알림이 없어서 문제가 있었음.
- 이것이 없어서 유저는 뒤로가기로 게임창을 벗어났으나, 게임
큐에서 나가지지 않는 등 사이드 이펙트가 있었음.
- componentWillUnmount 를 할 때, 게임을 나갔다는 메시지를 보낼 수 있게
하였음.
> [TL42-71] fix: 게임 창에서 벗어날 때, GAME_LEAVE_REQ.

- back-end/src/socket/game/constants/game.constants.ts
- back-end/src/socket/game/socket-game.service.ts
- back-end/src/socket/socket.gateway.ts
1. 클라이언트가 게임 화면을 '뒤로 가기' 등으로 나갈 때, 클라이언트의
화면은 더 이상 게임 화면이 아님.
2. 그러나 이에 대한 아무런 알림이 없기에 클라이언트가 게임 화면을 보고
있는지, 아니면 뒤로 가기를 눌렀는지 서버는 알 방도가 없었음.
3. 이에 대해서 클라이언트가 더 이상 게임 화면을 보고 있지 않다면
게임을 나갔다는 메시지를 보내도록 수정하였음.
- 이에 대한 서버의 처리 기능을 추가하였음.
- leaveQueue 함수를 만들어서 이미 사용자가 큐에 있다면 그 사용자를
큐에서 제거함.
- disconnect 함수에서 leaveQueue 함수를 호출하게 하여, 모든 방에서 퇴장
시키는 로직이 동작할 때, 함께 큐에서도 제거하게 하였음.
- GAME_LEAVE_REQ 메시지를 받으면, 게임에서 나간 것(탈주 한 것)으로
간주함. 따라서 disconnect 함수를 호출하게 하였음.
> [TL42-69] fix: GAME_LEAVE_REQ 메시지 처리

- front-end/src/UI/Templates/Loading/index.tsx
- 기존에 어색하게 생긴 로딩 화면을 검은 배경에 로고를 붙이고, 내용을
화면 가운데로 정렬시킴.
> [TL42-85] feat: 로딩 화면에 디자인 추가

- front-end/src/App.tsx
- front-end/src/Hooks/useSocket.tsx
- 웹 소켓을 연결 할 때, 유저 토큰을 보낼 수 없어서 사용자를 식별할 수
없는 문제가 있었음.
- 이를 해결 하기 위해, URL을 파싱하여서 'user' 값을 웹소켓 쿼리로
보내는 기능을 추가함.
- 나중에는 유저 토큰을 URL에서 파싱해오는 것이 아니라, 백엔드 API를
통해 얻어올 것임.
http://localhost:3001/?user=temporary-user-token
이런 식으로 사용하면 됩니다.
> [TL42-91] feat: 웹소켓 연결 시 쿼리 받게 수정

- front-end/src/App.tsx
- front-end/src/UI/Atoms/TabListElement/index.tsx
- front-end/src/UI/Organisms/MainSocialSocial/index.tsx
- front-end/src/UI/Organisms/MainSocialTabPanelChat/index.tsx
- front-end/src/UI/Organisms/MainSocialTabPanelFriend/index.tsx
- front-end/src/UI/Organisms/MainSocialTabPanelNotification/index.tsx
- front-end/src/UI/Organisms/MainSocialTabs/index.tsx
- front-end/src/UI/Templates/MainSocial/index.tsx
- 아이콘 및 텍스트를 갖는 탭 리스트 분자 컴포넌트를 만듦.
- `/game` 경로는 게임을 위한 경로로 전달시킴.
- 이외의 모든 경로는 `Main` 컴포넌트로 전달시켜 처리하도록 함.
- 친구, 알림, 대화로 나누어진 탭 레이아웃을 추가.
- `FriendTab`, `NotificationTab`, `ChatTab` 세 가지의 탭 유기체로 구분됨.
- 네이밍을 일관성 있게 수정함.
> [TL42-89] fe 친구 알림 대화 탭 분리 및 react router dom 연결

- front-end/src/UI/Atoms/ContextMenu/index.tsx
- front-end/src/UI/Organisms/MainSocialTabPanelFriend/index.tsx
- front-end/src/UI/Templates/UserContextMenu/index.tsx
- Github 공개 ContextMenu 라이브러리를 사용해서, 사용자를 우클릭 할 때
나오는 메뉴에 대한 템플릿을 구현.
- 'mode' props를 사용해서 친구 또는 채팅에 대한 컨텍스트 메뉴를 구분할
수 있게 함.
- 추후, '나' 와 '상대 유저' 에 대한 값도 props를 통해 넘겨서, 검사할
수 있게 하면 좋을 듯?
> [TL42-92] feat: 사용자 컨텍스트 메뉴 템플릿 추가

- front-end/src/UI/Molecules/SpectateMenu/index.tsx
- front-end/src/UI/Templates/UserContextMenu/index.tsx
컨텍스트 메뉴 중 관전하기에 실패했을 경우 나오는 창 컴포넌트를 추가.
> [TL42-111] feat: 관전실패시 나오는 창 추가

- front-end/src/Hooks/useAddFriend.ts
- front-end/src/Queries/Users/Search.ts
- front-end/src/UI/Molecules/SearchFriendResultElement/index.tsx
- 실제 axios로 요청을 보내도록 수정.
- alert삭제. 대신 오류 발생 시, WarningAlertDialog를 통해 에러를 출력.
- 추후 react-query 기능을 사용해서, 친구리스트 캐시를 모두
비우는 동작을 수행해야 함.
> [TL42-151] fix: 실제 요청을 보내도록 수정

- front-end/src/UI/Molecules/ModifiableUserName/index.tsx
닉네임을 Input으로 받는 것을 form으로 감싼 후
axios.patch를 이용해 닉네임 변경하는 로직 추가
닉네임이 중복일 경우 alert를 띄우도록 함
https://user-images.githubusercontent.com/71748476/183853407-3dced99e-aed1-4772-92c4-c617f5f41180.mov
> [TL42-142] feat: Input을 form으로 감싸고 닉네임 변경

- back-end/src/alert/alert.Repository.ts
- back-end/src/alert/alert.service.ts
- back-end/src/chat/chat.controller.ts
- back-end/src/chat/chat.room.repository.ts
- back-end/src/chat/chat.service.ts
- back-end/src/chat/chat.user.repository.ts
- back-end/src/dm/dm.repository.ts
- back-end/src/friend/friend.controller.ts
- back-end/src/friend/friend.repository.ts
- back-end/src/friend/friend.service.ts
- back-end/src/game/game.repository.ts
- back-end/src/users/users.controller.ts
- back-end/src/users/users.repository.ts
- friend 요청 자기자신에게 보냈을시 예외처리
- friend 요청, 수락, 거절, 차단 return void로 수정, 따로 받아볼 데이터가 없음
- friend 수락과 거절은 응답에 대해 회신할때 닉네임이 변경될 수 있으므로 userId로 교체
- friend 검색은 프론트에서 처리하기로함
- friend exception 각 상황에 맞게 변경
- user/search는 404 말고 빈 배열로 전달해 주는 식으로 변경
- 모든 save에서 500 에러 핸들링 넣어줌
- friend 전체 조회시 User[] return 으로 변경, 친구 없을 때 빈 객체로 수정함
> [TL42-148] feat: Friend API 정리

- front-end/src/UI/Molecules/ModifiableUserName/index.tsx
- front-end/src/UI/Organisms/UserProfileInfo/index.tsx
- front-end/src/UI/Pages/OTPRevise/index.tsx
스문님이 워닝알러트다이얼로그 훅을 완성하시면 그것을 이용해서
에러시에 행동을 추가하는 것이 남았다. 현재 patch를 이용해서 백엔드에
보냈을 때 로컬에 저장되는 것과 status 200을 반환하는 것으로 보아
프로필 이미지 수정이 잘 될 것 같다. 그리고 otprevise에서 2차인증
해제할때도 큐알코드를 보여줘야할 것 같아서 박스를 넣었다.
modifiableusername 에서는 async await을 안쓰기위해 스문님의 조언을얻어
setsubmitting 함수를 성공시 실패시 각각 사용하도록 코드를 수정하였다.
> [TL-42 162] feat: 프로필 이미지 수정기능 외 사소한 수정

- back-end/src/users/constants/multer.options.ts
- back-end/src/users/entities/user.entity.ts
- back-end/src/users/users.repository.ts
- front-end/src/UI/Molecules/ModifiableUserName/index.tsx
- front-end/src/UI/Organisms/UserProfileInfo/index.tsx
queryClient.invalidateQueries 메서드를 이용해서
바로 변경되게 하였다. 하지만 사진부분에서 파일 이름이
계속 똑같은 이슈가 있어서 똑똑한 리액트가 변경된게 없다고 생각해버렸다.
그래서 백엔드 코드도 같이 수정했다. 파일 이름 뒤에 날짜를 붙이고
새 파일이 있으면 이전파일은 지우도록 백엔드 코드에 추가를 해놓았다.
> [TL42-190] fix : 프로필 사진 변경시 바로 렌더링

- back-end/src/users/users.repository.ts
첫번째 조건문은 현재 저장하고있는 default 이미지를 지우지
않기 위한 코드이고 추가된 조건문은 현재 프로필 이미지로 저장되어있는
파일이 존재하는지 여부를 확인하는 코드입니다. 추가된 코드로 인해
postgres 컨테이너를 삭제하고 다시 시작할 필요가 없어질 것입니다.
> [TL42-191] refactor: 이미지 지우기전 확인하는 코드

- front-end/src/Props/ChannelProps.ts
- front-end/src/UI/Molecules/ChannelElement/index.tsx
- front-end/src/UI/Organisms/MainSocialTabPanelChat/index.tsx
채팅방 정보를 get 해올 때 count가 넘어오는데
그 count가 현재 인원수 입니다. 그래서 적용하였습니다.
> [TL42-197] feat: 백엔드에서 주는 현재인원수 적용

- front-end/src/Props/RecordProps.ts
- front-end/src/Props/UserProfileProps.ts
- front-end/src/UI/Organisms/UserMatchHistory/index.tsx
- front-end/src/UI/Pages/Profile/index.tsx
- front-end/src/UI/Templates/ProfileContent/index.tsx
백엔드에서 줄거라 기대하는 정보를 바탕으로
RecordProps 작성. 나중에 바뀔 수 있음.
유저 매치기록이 3개이상일 경우 스크롤 되도록 스타일 수정
전적기록 받아와서 하위 컴포넌트들 프롭스로 전달
https://user-images.githubusercontent.com/71748476/184469145-3f5d3074-1933-4856-8c3b-3a94817d0ef8.mov
> [TL42-193] feat: 유저 전적 정보

- back-end/.env.dev
- back-end/.env.prod
- back-end/src/auth/auth.controller.ts
- http://localhost:3001/ 로 하드코딩된 리다이렉션 주소의 .env화
> [TL42-199] fix: 인증 후 리다이렉션을 .env에서

- front-end/src/Hooks/useChat.tsx
- front-end/src/Hooks/useToastedChat.tsx
- front-end/src/UI/Organisms/ChatHeader/index.tsx
useChat과 useToastedChat 에서 dependency문제로 계속해서
useEffect가 돌아가는 현상 수정(by. smun)
ChatHeader에서 roomType에 따라 다르게 렌더링 하도록 코드수정
https://user-images.githubusercontent.com/71748476/184822273-16b8c6d7-4942-401c-9a1f-d17ac95c3eb5.mov
> [TL42-213] fix: DM 비밀번호 변경 못하게 수정

- front-end/src/Props/RecordProps.ts
- front-end/src/UI/Organisms/UserMatchHistory/index.tsx
RecordProps 및 사용하는 곳에서 코드 간단 수정
> [TL42-XX] fix: 백엔드에서 넘어오는 변수명 대로 수정

- back-end/src/friend/friend.module.ts
- back-end/src/friend/friend.service.ts
- back-end/src/socket/chat/constants/state.user.enum.ts
- back-end/src/socket/chat/dto/state.update.user.notify.dto.ts
- back-end/src/socket/class/user.connected.class.ts
- back-end/src/socket/game/constants/game.constants.ts
- back-end/src/socket/socket-state.service.ts
- back-end/src/socket/socket.gateway.ts
- back-end/src/socket/socket.module.ts
- front-end/src/UI/Molecules/FriendElement/index.tsx
- 순환참조를 해결하기 위해 `SocketStateService` 를 새로 구현.
- 온라인, 오프라인, 게임중, 관전중 상태 모두 처리.
- 실시간으로 유저의 온라인 상태를 친구들에게 보내줌.
- 친구 관계가 새로이 설정되었을때, 현재 친구의 온라인 상태를 즉시 확인 가능.
> [TL42-230] 실시간 친구 상태의 백엔드 구현

- front-end/src/Hooks/useApp.ts
- front-end/src/Hooks/useMe.ts
- front-end/src/Hooks/useMessage.ts
- front-end/src/Props/UserInfoProps.ts
- front-end/src/UI/Pages/InitialSetup/index.tsx
- 처음 닉네임 및 사진 설정 후, 설정 완료 버튼을 눌러서 저장한 후에 메인
페이지로 넘어갈 수 있음.
- 사진 및 닉네임에서 오류 (닉네임 중복 등)가 발생하면 넘어가지지 않음.
> [TL42-206] feat: 첫 로그인 설정 페이지 구현

- front-end/src/UI/Organisms/ChatMembers/index.tsx
- front-end/src/UI/Organisms/MainSocialMyProfile/index.tsx
- front-end/src/UI/Organisms/MainSocialTabPanelFriend/index.tsx
- front-end/src/UI/Templates/UserContextMenu/index.tsx
- me를 ChatMembers에서 props로 넘겨주도록 변경
- member의 role을 추가해서 me의 role과 target의 role에 따라 다르게
렌더링 되도록 변경
> [TL42-245] feat: 컨텍스트 메뉴 역할따라 렌더링

- front-end/src/UI/Molecules/ModifiableUserName/index.tsx
채팅방 안에서도 닉네임 변경이 가능하기 때문에
무조건 /users/nickname으로 navigate하던 것을 변경
> [TL42-XX] refactor: 이름변경후 navigate url 수정

- front-end/src/Hooks/useBlocks.ts
- front-end/src/Props/BlocksProps.ts
- front-end/src/Queries/Blocks/All.ts
- front-end/src/UI/Molecules/BlockMenu/index.tsx
- front-end/src/UI/Templates/UserContextMenu/index.tsx
친구여야만 차단여부를 알 수 있던 것을 back에서 본인의
차단유저 리스트를 api로 받아와서 확인할 수 있도록 함.
useBlocks 훅으로 언제든 불러올 수 있음.
성공 시에는 토스트로 띄움.
> [TL42-259] fix: 차단하기 기능

- front-end/src/Hooks/useChatRoomInfo.ts
- front-end/src/Props/UserProfileProps.ts
- front-end/src/UI/Pages/Profile/index.tsx
- 채팅방에서 상대 정보보기 눌렀을 때, 내 랭크스코어가 나오는 문제 해결
- 채팅방 생성후 나간다음 다른방 입장시 오류나던 것 해결. 클리어 부분에서
setRequest로 타입을 조인으로 바꿔줌.
> [TL42-XX] fix: 랭크스코어, 채팅방 생성 후 입장

- front-end/src/UI/Molecules/ProtectedChannelElement/index.tsx
- 채팅방 비번입력을 한 후 초기화 및 setSubmitting을 false로 해주지
않아서 방을 나간 후 다시 들어가려고 누르면 이전 상태에서 제출된 상태로
계속 동그라미 돌던 문제 수정
> [TL42-XX] fix: 채팅방 비번입력창 제출 후 초기화
