front-end/package-lock.json, front-end/package.json
- IDE에서 자동완성을 위해 @types/styled-components 패키지 설치.
=> TL42-57 chore. @types/styled-components 추가

front-end/src/UI/Atoms/LogInButton/index.tsx
UI/ATOMS/LoginButton/index.tsx를 추가했다.
=> TL42-62 feat. 로그인 버튼 추가

front-end/package-lock.json, front-end/package.json, front-end/src/App.tsx, front-end/src/UI/Atoms/BlackBox/index.tsx, front-end/src/UI/Atoms/LogInButton/index.tsx, front-end/src/index.tsx
- 오늘의 삽질은 bootstrap을 쳐내기 위함이었습니다.
=> style. 망할 bootstrap 폐기 후 chakra-ui 채용

.env, back-end/.dockerignore, back-end/.env.dev, back-end/Dockerfile, back-end/package-lock.json, back-end/src/app.module.ts, config/nginx/reverse-proxy.conf, docker-compose.yml, front-end/.dockerignore, front-end/Dockerfile
- Frontend, Backend, Postgres, pgadmin, nginx
- docker-compose.yml, Dockerfile 파일 생성.
- Nest.JS 쪽에서 Postgres로 연결이 안되는 문제가 발생.
- 따라서, 임시로 TypeORM 관련 모듈을 모두 주석처리 하였음.
=> TL42-14 chore. Docker-compose 빌드 파일 추가

front-end/src/UI/Atoms/SearchBar/index.tsx
atom component 중 하나인 검색창 component를 추가했다.
=> [TL42-74] feat: SearchBar 추가

front-end/package-lock.json, front-end/package.json
package.json 과 package-lock.json 추가합니다.
=> [TL42-82] fix: Search Bar 빌드가 안되는거 수정

front-end/src/UI/Molecules/FriendTap/index.tsx
오른쪽 친구 탭 중 친구 프로필 사진 + 접속상태 + 닉네임 보여주는
component를 추가했다
=> [TL42-76] feat: FriendTap molecule component 추가

front-end/src/App.tsx, front-end/src/UI/Organisms/MainSocialMyProfile/index.tsx, front-end/src/UI/Organisms/MainSocialSocial/index.tsx, front-end/src/UI/Pages/Main/index.tsx, front-end/src/UI/Templates/MainSocial/index.tsx, front-end/src/UI/Templates/MainStandby/index.tsx
- front-end/src/App.tsx: 메인 페이지 구성을 위해 Main 컴포넌트를 사용
- front-end/src/Main/index.tsx: 소셜 사이드바 폭 고정, mainStandby는 flexible.
- front-end/src/Templates/MainStandby: 테스트 위해 빈 컴포넌트 제작.
- front-end/src/Templates/MainSocial: Myprofile과 그 외의 공간으로 나눔.
- front-end/src/Organisms/MainSocialMyProfile: MyProfile 컴포넌트.
- front-end/src/Organisms/MainSocialSocial: 나머지 기능들 구현하게 될 컴포넌트.
**디렉토리 구조나 컴포넌트 이름/위치 등은 피드백주시면 수정해서 다시 풀리퀘스트 올리겠습니다**
=> [TL42-73] feat: MyProfile 컴포넌트 구현

front-end/src/UI/Molecules/ChannelElement/index.tsx
비밀번호 걸린 여부를 boolean으로,
채널이름을 string으로,
현재 접속 인원과 최대 접속 가능 인원을 number로 받아
렌더링 해주는 컴포넌트 추가
=> [TL42-79] feat: ChannelElement 추가

front-end/src/UI/Atoms/AcceptanceButton/index.tsx
- isChecked, isAccepted 두 개로 관리되던 State를 하나의 객체로
합쳤습니다.
- AcceptDeclineButtons에서 onClick시 함수를 인라인으로 바꿨습니다.
=> [TL42-77] refactor: AcceptanceButton컴포넌트 리팩토링

front-end/src/UI/Molecules/NotificationElement/index.tsx
props로 userName을 받아 친구 요청이 왔음을 알려주는
컴포넌트를 추가.
=> [TL42-78] feat: NotificationElement 추가

front-end/src/UI/Organisms/PopoverButton/index.tsx
안에 내용 컴포넌트와 버튼의 아이콘을 지정할 수 있는 Popover(팝업
메뉴)컴포넌트입니다.
=> [TL42-75] feat: Popover 컴포넌트 제작

front-end/src/UI/Molecules/CreateChannel/index.tsx, front-end/src/UI/Molecules/FriendSearch/index.tsx, front-end/src/UI/Organisms/PopoverButton/index.tsx
스타일링은 끔찍합니다..
검색한 친구 리스트는 API연동이 돼야 어떻게 할 수 있을것 같아서 안됐습니다.
Popover컴포넌트에 다른 컴포넌트를 넣어주는걸 children으로 하는 것으로 변경했습니다.
=> Tl42 87 fe popover 컴포넌트 내용으로 들어갈 컴포넌트 제작

front-end/src/UI/Molecules/FriendElement/index.tsx, front-end/src/UI/Organisms/ElementList/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelChat/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelFriend/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelNotification/index.tsx, front-end/src/UI/Organisms/MainSocialTabs/index.tsx
=> Tl42 80 fe molecule 들이 모인 list organism component 제작

front-end/src/UI/Atoms/ContextMenu/index.tsx, front-end/src/UI/Organisms/MainSocialMyProfile/index.tsx, front-end/src/UI/Templates/UserContextMenu/index.tsx
- 유저 컨텍스트의 각 메뉴에 아이콘을 추가.
- 기존의 'contextmenu' 이벤트 외에, 마우스 왼클릭 이벤트인 'click' 이벤트도 추가.
=> [TL42-92] feat: 각 메뉴 아이콘 및 클릭 이벤트 추가

front-end/src/UI/Atoms/ContextMenu/index.tsx, front-end/src/UI/Molecules/CreateChannel/index.tsx, front-end/src/UI/Molecules/FriendElement/index.tsx, front-end/src/UI/Molecules/FriendSearch/index.tsx, front-end/src/UI/Organisms/ElementList/index.tsx, front-end/src/UI/Organisms/MainSocialMyProfile/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelChat/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelFriend/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelNotification/index.tsx, front-end/src/UI/Organisms/MainSocialTabs/index.tsx, front-end/src/UI/Organisms/PopoverButton/index.tsx, front-end/src/UI/Pages/Main/index.tsx, front-end/src/UI/Templates/UserContextMenu/index.tsx
해당 작업 branch master 버전 누락으로 merge
=> 해당 작업 branch master 버전 누락으로 merge

back-end/src/socket/game/class/room.class.ts, back-end/src/socket/game/socket-game.service.ts, back-end/src/socket/socket.gateway.ts
- 기존 DB에 저장된 게임 id의 타입인 string으로 수정
=> [TL42-96] chore: 게임 서비스 create 함수 수정

back-end/src/socket/game/constants/game.constants.ts, back-end/src/socket/game/socket-game.service.ts, back-end/src/socket/socket.gateway.ts
- handleGameDecline 함수 추가
- game.constants.ts 파일에 있는 SocketEventName으로 응답 정의(초대, 거절에 추가)
=> [TL42-98] feat: 게임 초대 거절 handler 추가

front-end/src/Games/GameContext.ts, front-end/src/Games/InputManager.ts, front-end/src/UI/Pages/Game/index.tsx
별 것 없읍니다. touch~ 이벤트를 활용해서 터치 입력을 지원하게 되었읍니다.
=> 퐁 게임 터치 스크린 지원

front-end/src/UI/Molecules/FriendElement/index.tsx, front-end/src/UI/Molecules/NotificationElement/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelChat/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelFriend/index.tsx
=> Tl42 101 fe 컴포넌트 패딩 적용 안된것들 스타일링

back-end/src/chat/chat.controller.ts, back-end/src/chat/chat.module.ts, back-end/src/chat/chat.room.repository.ts, back-end/src/chat/chat.service.ts, back-end/src/friend/friend.service.ts, back-end/src/game/game.repository.ts, back-end/src/game/game.service.ts
- findAllChatRoom function 추가로 모든 채팅방 목록 가져온다.
- friend service에서 requestFriend 함수호출할때 await 안하는 것 수정
=> [TL42-116] feat: 모든 채팅방 목록 가져오는 기능 추가

back-end/.env.dev, back-end/src/chat/chat.controller.ts, back-end/src/chat/chat.module.ts, back-end/src/chat/chat.room.repository.ts, back-end/src/chat/chat.service.ts, back-end/src/friend/friend.service.ts, back-end/src/game/game.repository.ts, back-end/src/game/game.service.ts, front-end/Dockerfile, front-end/src/UI/Pages/OTPLogin/index.tsx
=>  switching the base 때문에 merge

back-end/src/chat/chat.controller.ts, back-end/src/chat/chat.room.repository.ts, back-end/src/chat/chat.service.ts, back-end/src/game/game.service.ts
- ChatRoom Object 를 반환
- 추후 데이터 정제시 교체 예정
=> TL42-119-be-chat-채팅방-정보-가져오기-rest-api

front-end/src/UI/Atoms/ContextMenu/index.tsx, front-end/src/UI/Molecules/InviteGameMenu/index.tsx, front-end/src/UI/Templates/InviteGame/index.tsx, front-end/src/UI/Templates/UserContextMenu/index.tsx
=> Tl42 106 fe game 게임 초대 게임 생성 컴포넌트 제작

back-end/package-lock.json, back-end/package.json, back-end/src/app.module.ts, back-end/src/chat/chat.controller.ts, back-end/src/chat/chat.module.ts, back-end/src/chat/chat.room.repository.ts, back-end/src/chat/chat.service.ts, back-end/src/chat/chat.user.repository.ts, back-end/src/chat/dto/create.chat.room.dto.ts, back-end/src/chat/entities/chat.user.entity.ts, back-end/src/config/typeorm.config.factory.ts, back-end/src/middleware/logger.middleware.ts
- 채팅방 안의 채팅방 유저 연동해서 생성되도록 기능 추가
- 로거 미들웨어 추가
=> TL42-130-be-chat-채팅방-생성되면-채팅유저도-생성되도록-구현

back-end/.eslintrc.js, back-end/src/chat/chat.controller.ts, back-end/src/chat/chat.room.repository.ts, back-end/src/chat/chat.service.ts, back-end/src/chat/chat.user.repository.ts, back-end/src/chat/dto/chat.room.dto.ts, back-end/src/chat/dto/update.role.dto.ts
- dto, repo, controller, service 생성
- 테스트는 아직
=> [TL42-121] feat: 채팅 유저 역할 변경 rest API

front-end/src/UI/Molecules/FriendElement/index.tsx, front-end/src/UI/Molecules/NotificationElement/index.tsx, front-end/src/UI/Organisms/MainSocialMyProfile/index.tsx
borderRadious 추가해서 디자인 통일감 높혔습니다.
=> [TL42-134] refactor: 디자인 수정

back-end/package-lock.json, back-end/package.json, back-end/src/socket/game/dto/chat.dto.ts, back-end/src/socket/game/dto/req/game.create.req.dto.ts, back-end/src/socket/socket.gateway.ts, back-end/src/socket/socket.module.ts, back-end/src/socket/socket.service.ts
- 단순한 ChatRoom join, leave, sendMessage
=> [TL42-123] feat: socket 기초 기능 셋팅

front-end/package-lock.json, front-end/package.json, front-end/src/Hooks/useChat.tsx, front-end/src/UI/Organisms/ChatBody/index.tsx, front-end/src/UI/Pages/Chat/index.tsx, front-end/src/UI/Pages/ChatModal/index.tsx, front-end/src/UI/Pages/Main/index.tsx, front-end/src/UI/Pages/RoutedModalExample/index.tsx, front-end/src/UI/Templates/ChatModal/index.tsx, front-end/src/UI/Templates/RoutedModal/index.tsx, front-end/src/UI/Templates/UserContextMenu/index.tsx
https://user-images.githubusercontent.com/40755203/182764863-fc32a241-bcba-483a-a3ac-ef45cdaf3ddc.mp4
=> [TL42-112] [FE] 채팅유저->정보보기 수정, 채팅 올라오는 기능.

front-end/src/Hooks/useChat.tsx, front-end/src/Props/ChatInfoProps.tsx, front-end/src/UI/Atoms/ScrollableVStack/index.tsx, front-end/src/UI/Molecules/ChannelElement/index.tsx, front-end/src/UI/Molecules/FriendElement/index.tsx, front-end/src/UI/Organisms/ChatHeader/index.tsx, front-end/src/UI/Organisms/ChatMembers/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelChat/index.tsx, front-end/src/UI/Pages/Chat/index.tsx, front-end/src/UI/Pages/Main/index.tsx, front-end/src/UI/Pages/RoutedModalExample/index.tsx
=> Tl42 104 fe friend dm 클라이언트 컴포넌트 제작

back-end/src/chat/chat.controller.ts, back-end/src/chat/chat.module.ts, back-end/src/chat/chat.service.ts, back-end/src/chat/chat.user.repository.ts, back-end/src/chat/dto/chat.dto.ts, back-end/src/chat/entities/chat.user.entity.ts, back-end/src/socket/game/dto/chat.dto.ts, back-end/src/socket/socket.gateway.ts, back-end/src/socket/socket.module.ts, back-end/src/socket/socket.service.ts
- rest API로 구현
- 음소거 setTimeout으로 구현
- 음소거 해제 구현
- 채팅 보내기 구현 및 음소거 필터 적용
=> TL42-122-be-chat-채팅방-음소거-설정-해제-rest-api

front-end/src/UI/Pages/Chat/index.tsx
=> DM에서 참가자에 왕관 씌워진 것 수정

front-end/package-lock.json, front-end/package.json, front-end/src/UI/Molecules/CreateChannel/index.tsx
- 채널을 생성하는 폼 구현.
- Yup 패키지를 사용해서 Formik과 연동해 유효성 구현
- 유효성체크 및 에러 메시지 출력.
아래는 채널 생성 유효성 검사를 위해 Yup을 사용한 코드.
```
const CreateChannelScheme = Yup.object().shape({
name: Yup.string()
.required('채널명이 필요합니다.')
.min(4, '채녈명은 4글자 이상이어야 합니다.')
.max(20, '채널명은 20글자 이하이어야 합니다.'),
max: Yup.number()
.typeError('최대 인원을 정수로 입력해주세요.')
.integer('최대 인원을 정수로 입력해주세요.')
.required('최대 인원을 입력해 주세요.')
.min(2, '방의 최대 인원은 적어도 2명이어야 합니다.')
.max(100, '방의 최대 인원은 100을 초과할 수 없습니다.'),
password: Yup.string().max(
100,
'입장 비밀번호는 100자를 초과할 수 없습니다.',
),
});
```
=> [TL42-114] feat: 채팅방 생성 폼 및 실패 피드백

front-end/package-lock.json, front-end/package.json, front-end/src/UI/Molecules/ChangePasswordChannel/index.tsx, front-end/src/UI/Molecules/CreateChannel/index.tsx, front-end/src/UI/Organisms/ChatHeader/index.tsx, front-end/src/UI/Organisms/PopoverButton/index.tsx, front-end/src/UI/Templates/ChatModal/index.tsx
=> [TL42-118] [FE] [CHAT] 채팅방의 방 정보 수정 실패 피드백 화면

back-end/src/chat/chat.controller.ts, back-end/src/chat/chat.service.ts, back-end/src/chat/chat.user.repository.ts, back-end/src/socket/class/user.class.ts, back-end/src/socket/socket.gateway.ts, back-end/src/socket/socket.service.ts
- rest API가 아니라 소켓으로 처리되게끔 변경 필요함
=> [TL42-124] feat: 채팅방 나가는 경우 소켓 처리

front-end/src/Hooks/useChat.tsx, front-end/src/Hooks/useTargetUser.tsx, front-end/src/Hooks/useToastedChat.tsx, front-end/src/Props/ChatEvent.ts, front-end/src/UI/Molecules/AdminApproveMenu/index.tsx, front-end/src/UI/Molecules/BanMenu/index.tsx, front-end/src/UI/Molecules/MuteMenu/index.tsx, front-end/src/UI/Organisms/ChatMembers/index.tsx, front-end/src/UI/Organisms/MainSocialMyProfile/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelFriend/index.tsx, front-end/src/UI/Templates/ChatModal/index.tsx, front-end/src/UI/Templates/UserContextMenu/index.tsx
=> [TL42-117] [FE] [CHAT] 채팅에서 음소거 영구추방 당함 관리자 관련 피드백 컴포넌트 제작

front-end/src/UI/Molecules/GameInvitationModal/index.tsx
Modal을 통해서 나중에 활용 할 수 있는 GameInvitationModal컴포넌트를
제작하였음. Modal의 isOpen등을 나중에 가공해서 사용할 수 있도록
만들었다.
=> [TL42-115] feat: 게임 초대 컴포넌트 모달 구현

back-end/src/auth/auth.controller.ts, back-end/src/main.ts, back-end/src/users/users.controller.ts, front-end/package-lock.json, front-end/package.json, front-end/src/App.tsx, front-end/src/UI/Pages/Login/index.tsx, front-end/src/index.tsx
=> feat: 프론트엔드와 백엔드 로그인 연동

front-end/src/UI/Organisms/UserProfileInfo/index.tsx
제목 그대로 이미지를 받아오는 Input태그를 Formik을
이용하여 form으로 감싸주는 모양으로 수정. 나중에 이미지를
저장하는 방식을 정해서 onsubmithandler에 추가해주면 될 것 같다.
=> [TL42-153] refactor: Input태그 Formik으로 수정

front-end/src/UI/Molecules/TwoFAInput/index.tsx, front-end/src/UI/Pages/OTPLogin/index.tsx, front-end/src/UI/Pages/OTPRevise/index.tsx
=> Tl42 154 fe otp login form으로 감싸기

front-end/src/Props/UserSearchResultProps.ts, front-end/src/Queries/Users/Search.ts, front-end/src/UI/Molecules/SearchFriendResultElement/index.tsx, front-end/src/UI/Templates/FriendSearch/index.tsx
- 친구 추가 레이아웃 누락에 대한 구현
- useQuery를 사용해서 친구 검색 기능 구현
=> [TL42-151] feat: 친구추가 레이아웃 및 기능

front-end/src/UI/Organisms/UserProfileInfo/index.tsx
문제가 되는부분을 빠른시간안에 찾지 못할 듯 하여
다른분들의 작업에 영향이 없도록 원래대로 되돌린 후
다시 찾을 예정.
=> [TL42-153] fix: 일단 다시 원래대로 되돌림

front-end/src/UI/Organisms/UserProfileInfo/index.tsx
필드 컴포넌트 안에 name만 설정했더니 흰페이지만 뜨던
현상이 없어졌다.. 이유는 모르겠지만 일단 된다..
=> [TL42-153] fix: 폼으로 감싼경우 문제가 생기던 버그 수정

front-end/src/Hooks/useInviteGame.ts, front-end/src/Props/InviteGameProps.ts, front-end/src/Props/WarningDialogProps.ts, front-end/src/UI/Molecules/InviteGameMenu/index.tsx, front-end/src/UI/Templates/InviteGame/index.tsx
- Formik으로 감싸서, 게임 초대를 백엔드로 보낼 수 있게 함.
- 에러 발생 시, WarningAlertDialog 표시하도록 함. (axios로 요청)
- 훅 사용이 너무 많아져서 useInviteGame으로 따로 만듦.
=> [TL42-155] feat: InviteGame Formik화

back-end/src/alert/alert.Repository.ts, back-end/src/game/game.service.ts, back-end/src/users/entities/user.entity.ts, back-end/src/users/users.controller.ts, back-end/src/users/users.repository.ts, back-end/src/users/users.service.ts
=> TL42-146-be-user-api-정리

back-end/src/users/users.controller.ts, back-end/src/users/users.repository.ts, back-end/src/users/users.service.ts
- 유저 검색 controller, service, repository 추가 완료
=> [TL42-146] feat: 유저 검색 api 추가

front-end/src/Hooks/useSocket.tsx, front-end/src/Queries/QueryBuilder.ts, front-end/src/Queries/Users/Me.ts, front-end/src/Queries/Users/Search.ts, front-end/src/UI/Organisms/MainSocialMyProfile/index.tsx, front-end/src/UI/Templates/MainSocial/index.tsx
- 반환형을 지정해서 커스터마이징 가능한 BuildQuery 유틸리티 구현.
- /users/me, /users/search API를 사용하는 기능에 대해서 BuildQuery로
만들어진 쿼리를 사용하도록 수정.
=> Tl42 140 fe react query 라이브러리 사용할 수 있게 설정

front-end/src/UI/Atoms/SearchBar/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelFriend/index.tsx
https://user-images.githubusercontent.com/69182505/183826737-ba2f3e43-31ab-48fd-8c3d-89a18e8b2173.mov
Uploading Screen Recording 2022-08-10 at 3.01.57 PM.mov…
Special thanks to JangBalJang...
=> Tl42 144 fe search bar atom component 리팩토링

back-end/src/chat/chat.controller.ts, back-end/src/custom/typeorm.decorator.ts, back-end/src/friend/friend.controller.ts, back-end/src/friend/friend.repository.ts, back-end/src/friend/friend.service.ts
- api 수정
- 친구 검색 기능 추가
- 친구 목록 가져오기 기능 추가
=> [TL42-148] feat: 친구 API 수정 및 검색, 조회 추가

front-end/src/App.tsx, front-end/src/Hooks/useLogout.tsx, front-end/src/UI/Molecules/LogoutMenu/index.tsx, front-end/src/UI/Templates/UserContextMenu/index.tsx
- 브라우저의 Authentication 쿠키를 날리는 방식으로 로그아웃을 구현.
=> [TL42-157] feat: 로그아웃 기능 구현

front-end/src/Hooks/useAddFriend.ts, front-end/src/Hooks/useSocket.tsx, front-end/src/Hooks/useTime.ts, front-end/src/Props/NotificationProps.ts, front-end/src/Queries/Alerts/All.ts, front-end/src/Queries/Friends/All.ts, front-end/src/UI/Molecules/AcceptanceButton/index.tsx, front-end/src/UI/Molecules/FriendElement/index.tsx, front-end/src/UI/Molecules/NotificationElement/index.tsx, front-end/src/UI/Molecules/SearchFriendResultElement/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelFriend/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelNotification/index.tsx
- 알림에서 useQuery를 사용해서 알림을 받아오고, 표시할 수 있도록 수정.
- 친구 추가 및 목록을 받아서 출력시킬 수 있게 하였음. 추후에 백엔드쪽
로직과 URL이 변경되면, 그것에 맞게 수정시키면 될 예정.
=> [TL42-158] feat: 알림, 친구 기능 일부

back-end/src/alert/alert.Repository.ts, back-end/src/alert/alert.controller.ts, back-end/src/alert/alert.service.ts, back-end/src/alert/dto/alert.dto.ts, back-end/src/alert/entities/alert.entity.ts
- response에 필요한 데이터만 AlertDto로 전송
=> TL42-159-be-alert-알람-전체-조회-api-정리

back-end/src/alert/dto/alert.dto.ts, back-end/src/dm/dm.controller.ts, back-end/src/dm/dm.repository.ts, back-end/src/dm/dm.service.ts, back-end/src/dm/dto/dm.dto.ts, back-end/src/dm/dto/send.dm.dto.ts, back-end/src/friend/friend.service.ts
- 친구 요청 상태일때 DM 보내지는거 수정
- response에 필요한 데이터만 DmDto로 전송
=> [TL42-160] feat: DM 전체 조회 기능 수정

front-end/src/Props/UserProfileProps.ts, front-end/src/Queries/Users/Profile.ts, front-end/src/UI/Molecules/UserMatch/index.tsx, front-end/src/UI/Organisms/UserMatchHistory/index.tsx, front-end/src/UI/Pages/Main/index.tsx, front-end/src/UI/Pages/Profile/index.tsx, front-end/src/UI/Templates/ProfileContent/index.tsx, front-end/src/UI/Templates/UserContextMenu/index.tsx
https://user-images.githubusercontent.com/67667723/184065239-b58cb88d-2718-426d-80dd-4d92e209bcd1.mov
=> Tl42 143 fe profile component 백엔드에서 데이터 받아 오는걸로 수정

front-end/src/Hooks/useAddFriend.ts, front-end/src/Hooks/useInviteGame.ts, front-end/src/Hooks/useWarningDialog.tsx, front-end/src/UI/Molecules/SearchFriendResultElement/index.tsx, front-end/src/UI/Templates/ChangePasswordChannel/index.tsx, front-end/src/UI/Templates/CreateChannel/index.tsx, front-end/src/UI/Templates/InviteGame/index.tsx
- 기존에 WarningAlertDialog 사용이 번잡한 것을 useWarningDialog 훅을
만드는 것으로 리팩토링.
https://github.com/42TransLand/ft_transcendence/blob/a2113700d3395fb5f1151c5f946ae141c00556da/front-end/src/UI/Templates/CreateChannel/index.tsx#L33-L49
https://github.com/42TransLand/ft_transcendence/blob/8c7731e577e1e3aaba3940b628a94fc79eba79f6/front-end/src/UI/Templates/CreateChannel/index.tsx#L33-L45
=> [TL42-172] refactor: WarningAlertDialog 리팩토링

front-end/src/Props/NotificationProps.ts, front-end/src/Queries/Alerts/All.ts, front-end/src/Queries/Friends/Accept.ts, front-end/src/Queries/Friends/All.ts, front-end/src/Queries/Friends/Reject.ts, front-end/src/Queries/MutationBuilder.ts, front-end/src/UI/Molecules/AcceptanceButton/index.tsx, front-end/src/UI/Molecules/FriendElement/index.tsx, front-end/src/UI/Molecules/NotificationElement/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelFriend/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelNotification/index.tsx
- 알림에서 친구 요청을 수락하고, 거절하는 기능을 백엔드와 연결.
=> [TL42-170] [FE] [FRIEND] 친구 수락 및 거절 기능

front-end/src/UI/Molecules/ModifiableUserName/index.tsx
WarningAlertDialog 사용하던 방식을 스문님이 만든
커스텀훅을 이용하는 것으로 변경
=> [TL42-173] refactor: ModifiableUserName refactor

front-end/src/Hooks/useFriends.ts, front-end/src/UI/Templates/UserContextMenu/index.tsx
- 현재 내 친구 리스트를 가져오는 useFriends 훅 추가
- 컨텍스트 메뉴에서, 내 친구 리스트에 해당 유저가 포함되어 있다면,
친구추가 메뉴를 표시하지 않게 함.
=> [TL42-171] feat: 친구 상태일때는 친구추가 메뉴 숨김

back-end/src/game/constants/game.mode.enum.ts, back-end/src/game/dto/game.create.dto.ts, back-end/src/game/entities/game.entity.ts, back-end/src/game/game.repository.ts, back-end/src/game/game.service.ts, back-end/src/socket/game/class/room.class.ts, back-end/src/socket/game/dto/req/game.match.dto.ts, back-end/src/socket/game/dto/res/game.create.res.dto.ts, back-end/src/socket/game/dto/res/game.join.res.dto.ts, back-end/src/socket/game/socket-game.service.ts
=> [TL42-169] feat: 게임 enum 수정

back-end/src/friend/friend.controller.ts, back-end/src/friend/friend.repository.ts, back-end/src/friend/friend.service.ts
- 친구 해제 기능 추가
- 친구 요청 보내놓고 차단하면, PENDDING인 행 갱신이 아닌 새롭게 create 되는 문제 해결
=> [TL42-164] feat: 친구 해제 추가

front-end/src/UI/Molecules/ModifiableUserName/index.tsx, front-end/src/UI/Molecules/UserMatch/index.tsx, front-end/src/UI/Organisms/MainSocialMyProfile/index.tsx, front-end/src/UI/Organisms/UserMatchHistory/index.tsx, front-end/src/UI/Organisms/UserProfileInfo/index.tsx, front-end/src/UI/Templates/ProfileContent/index.tsx
=> Tl42 175 fe user match컴포넌트 스타일링

back-end/src/chat/chat.controller.ts, back-end/src/chat/chat.service.ts, back-end/src/chat/chat.user.repository.ts, back-end/src/chat/dto/chat.dto.ts, back-end/src/chat/dto/chat.room.dto.ts, back-end/src/chat/dto/update.role.dto.ts
- GetUset() 적용 및 api response 설명 미완성
- exception 처리
=> [TL42-179] feat: 채팅방 API

front-end/src/Props/ChannelProps.ts, front-end/src/Queries/Channels/All.ts, front-end/src/UI/Molecules/ChannelElement/index.tsx, front-end/src/UI/Organisms/ElementList/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelChat/index.tsx, front-end/src/UI/Templates/CreateChannel/index.tsx
https://user-images.githubusercontent.com/67667723/184105816-afaf2f2a-2ce1-4185-adb4-558ff7abd0b2.mov
=> Tl42 177 fe chat 채팅방 생성

back-end/src/chat/chat.service.ts
=> [TL42-179] fix: updateRole 수정

front-end/src/UI/Organisms/MainSocialTabPanelChat/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelFriend/index.tsx
- PopoverButton 바깥을 HStack, VStack말고 Flex 같은걸로 하나 더
감싸주면 문제가 해결됩니다.
- https://github.com/chakra-ui/chakra-ui/issues/3173
https://user-images.githubusercontent.com/40755203/184119050-e177f220-b068-450b-89f2-4df9a6fe8ddd.mov
=> [TL42-181] fix: Popover warning 수정

front-end/src/UI/Templates/CreateChannel/index.tsx
undefined가 컴포넌트의 프로퍼티의 값으로 들어가버리면
생기는 오류라고 알고 있다. 그래서 onsubmithandler에서 value
를 구체화하는 방식으로 코드를 수정하였다.
=> [TL42-182] fix : 채널 생성할때 입력시 오류 뜨던 것 수정

front-end/src/App.tsx, front-end/src/Games/GameContext.ts, front-end/src/Games/dto/constants/game.constants.ts, front-end/src/Games/dto/constants/game.mode.enum.ts, front-end/src/Games/dto/req/game.create.req.dto.ts, front-end/src/Games/dto/req/game.join.req.dto.ts, front-end/src/Games/dto/req/game.match.dto.ts, front-end/src/Games/dto/res/game.create.res.dto.ts, front-end/src/Games/dto/res/game.invite.res.dto.ts, front-end/src/Games/dto/res/game.join.res.dto.ts, front-end/src/Hooks/useGame.ts, front-end/src/Hooks/useInvitation.tsx, front-end/src/Hooks/useInviteGame.ts, front-end/src/Hooks/useSocket.tsx, front-end/src/Hooks/useWarningDialog.tsx, front-end/src/Props/InviteGameProps.ts, front-end/src/UI/Molecules/GameInvitationContent/index.tsx, front-end/src/UI/Molecules/InviteGameMenu/index.tsx, front-end/src/UI/Pages/Game/index.tsx, front-end/src/UI/Pages/Main/index.tsx, front-end/src/UI/Templates/InviteGame/index.tsx
- 다른 사람을 게임에 초대할 수 있음.
- 다른 사람의 게임 초대를 수락이나 거절할 수 있음.
- 일부 예외 케이스에 대한 처리가 추가적으로 필요함.
=> [TL42-176] [FE] [GAME] 게임 초대 및 수락을 백엔드와 연결

front-end/src/UI/Templates/CreateChannel/index.tsx
개발할때 편하게 하려고 써놓은 eslint-disable을
삭제하고 eslint에서 요구하는 대로 코드 삭제 및 수정
=> [TL42-XX] : eslint-disable 삭제

back-end/src/friend/friend.repository.ts, back-end/src/game/entities/game.entity.ts, back-end/src/game/game.repository.ts, back-end/src/game/game.service.ts, back-end/src/socket/game/class/room.class.ts, back-end/src/socket/game/dto/game.result.type.ts, back-end/src/socket/game/socket-game.service.ts, back-end/src/socket/socket.gateway.ts, back-end/src/users/entities/user.entity.ts
=> [TL42-178] feat: 게임 종료시 업데이트 추가

front-end/src/UI/Organisms/MainSocialMyProfile/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelChat/index.tsx, front-end/src/UI/Organisms/UserProfileInfo/index.tsx, front-end/src/UI/Pages/Profile/index.tsx, front-end/src/UI/Templates/ChangePasswordChannel/index.tsx
프로필 이미지 띄우기.. -> 아직은 새로고침을 해야 바뀜.. 이부분은 후에 해결해야할 것 같습니다.
이미지 확장자는 이제 모든 이미지파일 확장자를 다 받을 수 있게 변경
팝오버 높이 살짝 수정.
채팅방 안에서 비밀번호 변경하는 부분 로직 만들었습니다.
=> Tl42 185 fe 채팅방 비밀번호 변경 프로필 사진 띄우기

front-end/src/UI/Molecules/FriendElement/index.tsx, front-end/src/UI/Molecules/NotificationElement/index.tsx, front-end/src/UI/Organisms/MainSocialMyProfile/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelFriend/index.tsx
=> Tl42 186 fe friend 친구 프로필 사진 보이게 수정

back-end/.vscode/launch.json, back-end/src/socket/class/game.reservation.class.ts, back-end/src/socket/class/user.class.ts, back-end/src/socket/game/class/player.class.ts, back-end/src/socket/game/class/room.class.ts, back-end/src/socket/game/socket-game.service.ts, back-end/src/socket/socket.gateway.ts, back-end/src/users/users.repository.ts, front-end/src/Hooks/useInvitation.tsx, front-end/src/UI/Molecules/GameInvitationContent/index.tsx, front-end/src/UI/Pages/Main/index.tsx, front-end/src/UI/Templates/InviteGame/index.tsx
- 게임 초대, 수락 과정에서 한명이 나갈 경우 예외 케이스 처리
- 게임 중 한 명이 나갈 때, No winner 예외 문제 수정
- 게임 모드 및 승점 내기가 방 생성에서 반영되지 않는 문제 수정
=> [TL42-188] [FE/BE] [GAME] 예외 케이스 수정

back-end/.vscode/launch.json
vscode에서 NestJS를 디버깅할 수 있는 launch.json
=> Back end launch json

front-end/src/UI/Molecules/GameInvitationContent/index.tsx
=> [TL42-186] fix: 게임초대 이미지 뜸

back-end/src/chat/chat.controller.ts, back-end/src/chat/chat.room.repository.ts, back-end/src/chat/chat.service.ts, back-end/src/chat/constants/chat.type.enum.ts, back-end/src/chat/dto/chat.info.dto.ts, back-end/src/chat/entities/chat.room.entity.ts
- 채팅방 join시 count += 1 , leave시 count -= 1 추가
- 모든 채팅방 조회 할 때(findAllChatRoom) 비밀번호 전달 삭제하고 현재 입장된 인원수 추가
=> [TL42-194] refactor: 채팅방 현재 인원 추가

front-end/src/UI/Molecules/InviteGameMenu/index.tsx, front-end/src/UI/Templates/InviteGame/index.tsx
=> [TL42-180] refactor: 게임초대 팝업창 수정

front-end/src/UI/Organisms/ChatBody/index.tsx
새로운 함수를 만들 필요없이 원래 있던것에서 디펜던시만
바꿔도 잘 돌아가는 걸 확인하고 다시 고쳐봅니다.
=> [TL42-195] fe 채팅방 스크롤 수정

front-end/src/UI/Templates/ChangePasswordChannel/index.tsx, front-end/src/UI/Templates/CreateChannel/index.tsx
채팅방을 만들고 그 채팅방 비밀번호를 변경했을경우
실시간으로 다시 get 해오도록 바꿈
https://user-images.githubusercontent.com/71748476/184466847-e3f44257-35f6-4cd9-8b4e-164d0c7b0f3f.mov
=> [TL42-192] feat: invalidateQuery를 이용한 갱신

front-end/src/UI/Pages/OTPRevise/index.tsx
=> [TL42] refactor: two fa layout 수정

front-end/src/UI/Molecules/ModifiableUserName/index.tsx, front-end/src/UI/Organisms/UserProfileInfo/index.tsx, front-end/src/UI/Templates/ChangePasswordChannel/index.tsx
WarningDialogAlert에서 띄울 헤더메세지와 바디메세지를
백엔드에서 주는 err.response에 있는 메세지를 가져다쓰는 것으로
수정하였음
=> [TL42-198] refactor: 에러메세지 수정

back-end/src/chat/dto/create.chat.room.dto.ts
- 채팅방 이름 @IsNotEmpty(), @IsString() 추가
=> [TL42-201] refactor: 채팅방 이름 유효성 체크 추가

back-end/src/chat/chat.controller.ts, back-end/src/chat/chat.service.ts
=> [TL42-203] feat: 채팅방 강퇴 기능 추가

front-end/src/Props/ChatMemberProps.tsx, front-end/src/Props/ChatMemberRole.ts, front-end/src/UI/Atoms/ChatAvatar/index.tsx, front-end/src/UI/Molecules/ChatElement/index.tsx, front-end/src/UI/Molecules/ChatMemberElement/index.tsx, front-end/src/UI/Pages/Chat/index.tsx
- 긴 채팅이 올라올 경우, 사진이 찌그러지는 문제 수정
- 채팅방 방장 및 관리자에게 왕관 아이콘이 표시되도록 수정
- 채팅 관련 리팩토링
- ChatMemberRole을 'owner', 'admin', 'member' 로 쓰는 대신, enum으로 교체.
=> fix: 채팅 관련 문제 수정

front-end/src/WebSockets/dto/constants/socket.events.enum.ts
자잘한 회의록에 있는 이벤트네임대로 소켓이벤트네임
이넘 추가했습니다.
=> [TL42-XX] feat: 어제 회의한 이벤트네임 추가

back-end/src/users/users.controller.ts, back-end/src/users/users.repository.ts, back-end/src/users/users.service.ts
- 새로운 유저 들어왔을때 설정하려는 닉네임 기존에 있는 닉네임인지 조회할 수 있도록 추가
=> [TL42-208] feat: 닉네임 중복 조회 추가

front-end/src/Hooks/useMe.ts, front-end/src/Hooks/useSocket.tsx, front-end/src/Hooks/useTargetUser.tsx, front-end/src/Props/ChatMemberProps.tsx, front-end/src/Props/UserInfoProps.ts, front-end/src/Queries/Friends/Accept.ts, front-end/src/Queries/Friends/Reject.ts, front-end/src/UI/Molecules/AcceptanceButton/index.tsx, front-end/src/UI/Pages/Chat/index.tsx
사용자id가 모든 number형을 백엔드와 맞는 string으로 형변환
=> [TL-XX] refactor: 사용자ID number->string 형변환

front-end/src/Hooks/useSocket.tsx, front-end/src/UI/Molecules/FriendElement/index.tsx, front-end/src/UI/Organisms/MainSocialTabPanelFriend/index.tsx, front-end/src/WebSockets/dto/constants/user.state.enum.ts, front-end/src/WebSockets/dto/res/state.update.user.notify.dto.ts
- 실시간으로 친구의 상태를 갱신할 수 있는 FE 코드 추가.
- FriendOnlineState를 UserState로 리팩토링 하였음.
- UserContextMenu 리팩토링. flag를 사용해서 메뉴를 렌더링 하는 방식으로 수정하였음.
=> [TL42-220] feat: 실시간 친구 상태

back-end/src/auth/auth.service.ts, back-end/src/users/dto/user.profile.dto.ts, back-end/src/users/dto/user.record.dto.ts, back-end/src/users/users.repository.ts
- 래더 전적으로 변경
- 게임 고유 id, 래더 유무, 게임 모드 추가
=> [TL42-166] chore: 필요한 정보 추가

front-end/src/Props/RecordProps.ts, front-end/src/Props/UserProfileProps.ts, front-end/src/UI/Organisms/UserMatchHistory/index.tsx, front-end/src/UI/Pages/Profile/index.tsx, front-end/src/UI/Templates/ProfileContent/index.tsx
백엔드에서 넘겨주는 정보대로 RecordProps 수정.
백엔드에서 넘겨주는 이름대로 받아오는 변수이름 records에서
gameRecord로 변경. 그리고 정보에 맞게 렌더링 하도록 코드 수정
=> [TL42-223] fix: 백엔드에서 넘겨주는 정보 확인 후 적용

front-end/src/UI/Templates/UserContextMenu/index.tsx
- 오타 수정해서 친구 우클릭 해도 OTP 설정 메뉴 안뜨게 바꿨음.
- otp 수정할 때, 하드코딩으로 /otp/bylee로 url 되어있던거
/otp/targetName으로 바꿔주었음.
- 일단 menuDivider 빼줬음
=> [TL42-224] fix: 오타가 있었습니다

front-end/src/Props/UserProfileProps.ts, front-end/src/UI/Pages/Profile/index.tsx
=> [TL42-207] chore: 백엔드에서 받아온 정보로 전적리스트 연결

back-end/src/socket/game/socket-game.service.ts, back-end/src/users/dto/user.record.dto.ts, back-end/src/users/users.repository.ts, back-end/src/users/users.service.ts
- 전적 기록 시간 응답 추가
- 게임 스코어 갱신 추가
=> [TL42-225] feat: socre 갱신, 전적 기록 시간 추가

front-end/src/Props/RecordProps.ts, front-end/src/UI/Organisms/UserMatchHistory/index.tsx
=> [TL42-228] feat: 전적 시간 순서에 따라 렌더링

back-end/src/socket/game/socket-game.service.ts
=> [TL42-227] fix: 게임 최종 저장할때 문제 수정

back-end/src/socket/game/socket-game.service.ts
- 저장 직전에 winner, loser를 userRepository에서 각각 새로 가져온 후에
저장함.
=> [TL-XX] fix: 게임 전적 저장 터지는 것 수정

back-end/src/socket/game/socket-game.service.ts
남이 만든 게임을 내가 이겼을 경우
winner와 loser가 전부 다 내가 되는 현상을 막기위해
함수 호출 순서 변경
=> [TL42-XX] fix: 함수호출 변경

back-end/src/chat/chat.controller.ts, back-end/src/chat/chat.service.ts, back-end/src/socket/chat/constants/chat.user.update.type.enum.ts, back-end/src/socket/chat/dto/chat.update.user.notify.dto.ts, back-end/src/socket/socket.gateway.ts, back-end/src/socket/socket.service.ts
- ChatUserUpdateType enum 오타 수정
- owner 변경시 소켓 이벤트 보내도록 추가
=> [TL42-232] feat: owner 업데이트 시 소켓 이벤트 보내기 추가

back-end/src/socket/game/constants/game.constants.ts, back-end/src/socket/game/dto/req/game.spectate.req.dto.ts, back-end/src/socket/game/dto/res/game.spectate.res.dto.ts, back-end/src/socket/socket.gateway.ts
- handleGameSpectateRequest 추가 테스트 필요
=> [TL42-204] feat: 관전 기능 추가

back-end/src/dm/dm.controller.ts, back-end/src/dm/dm.service.ts, back-end/src/dm/dto/send.dm.dto.ts, back-end/src/friend/friend.service.ts, back-end/src/socket/class/user.class.ts, back-end/src/socket/socket.gateway.ts, back-end/src/socket/socket.service.ts
=> [TL42-235] feat: 디엠 소켓 연결

back-end/src/dm/dm.service.ts, back-end/src/socket/socket.gateway.ts, back-end/src/socket/socket.service.ts, front-end/src/Hooks/useSocket.tsx, front-end/src/UI/Pages/Chat/index.tsx, front-end/src/UI/Templates/DirectMessage/index.tsx, front-end/src/WebSockets/dto/res/chat.message.notify.dto.ts
- Socket 으로 DM수신시 dispatchChat 사용하여 Chat dispatch
- backend에서 DM송신 상대가 join 안되는 현상을 발견하여 수정
=> [TL42-238] feat: DM 수신 Socket 연결

back-end/src/dm/dm.service.ts, back-end/src/socket/socket.gateway.ts, back-end/src/socket/socket.service.ts
=> [TL42-239] fix: 디엠 소켓 연결 수정

front-end/package-lock.json, front-end/package.json, front-end/src/UI/Molecules/OTPInput/index.tsx, front-end/src/UI/Pages/OTPLogin/index.tsx, front-end/src/UI/Pages/OTPRevise/index.tsx
=> Tl42 209 fe 2 fa 2 차인증 기능 구현

front-end/src/Hooks/useSocket.tsx, front-end/src/UI/Molecules/LogoutMenu/index.tsx
- 로그아웃하면 친구들에게 오프라인으로 바로 안바뀌는 문제 => 소켓을 disconnect 하지 않아서 생기는 문제이기 때문에, 수정.
=> [TL42-XX] fix: 로그아웃시 소켓 연결 끊기 수정

front-end/src/Hooks/useSocket.tsx, front-end/src/UI/Organisms/MainSocialTabPanelFriend/index.tsx
- 게임 화면으로 들어가있는 상태에서는 친구의 상태 갱신 이벤트를 받지
못하는 문제 수정.
- 소켓이 전역적으로 메시지를 처리하여 저장할 수 있도록 수정함.
=> [TL42-XX] fix: 게임 상태 갱신 간헐적 오류 수정

back-end/src/users/entities/user.entity.ts, back-end/src/users/users.controller.ts, back-end/src/users/users.service.ts
- deprecated된 `substr` 함수를 `substring`으로 교체
- User에서 안쓰이는 요소들 삭제
=> Back end refactoring

back-end/src/socket/game/class/room.class.ts
- 네트워크 환경이 좋지 못한 곳에서, 이동이 튀는 문제 수정
=> [TL42-XX] fix: 플레이어 이동 알림 자기자신 제외

back-end/src/chat/chat.service.ts, back-end/src/chat/chat.user.repository.ts, back-end/src/chat/entities/chat.user.entity.ts
- 채팅방 나갈 때 owner인 경우 채팅방 삭제 안되는것 해결
- ChatUser에서 유저의 닉네임에 접근할 수 없어서 findChatUserNickname 추가 구현
- Mute 안되어 있는데 해제하려고 하는경우 400 에러
=> [TL42-243] fix: 채팅방 나갈때 에러 해결

back-end/src/chat/chat.service.ts
- 변경된 현재 상태가 공개면 true, 비밀방이면 false
=> [TL42-244] fix: 채팅방 공개 상태 변경 시 response 변경

front-end/src/Hooks/useChat.tsx, front-end/src/Props/ChatInfoProps.tsx, front-end/src/Props/ChatMemberRole.ts, front-end/src/UI/Molecules/ChannelElement/index.tsx, front-end/src/UI/Organisms/ChatHeader/index.tsx, front-end/src/UI/Organisms/ChatMembers/index.tsx, front-end/src/UI/Organisms/ChatModal/index.tsx, front-end/src/UI/Templates/ChatMessage/index.tsx, front-end/src/UI/Templates/DirectMessage/index.tsx, front-end/src/UI/Templates/RoutedModal/index.tsx
소문자로 사용하던 private, public, protect
대문자로 바꾸고 스문님이 댓글 다신것 보면서
일부 수정. checkType함수는 아직 어떻게 해야할지 모르겠음.
=> [TL42-XX] refactor: 백엔드와 동기화

front-end/src/Hooks/useChat.tsx, front-end/src/Hooks/useDirectMessageNotify.tsx, front-end/src/Hooks/useGameInviteNotify.ts, front-end/src/Props/ChannelProps.ts, front-end/src/Props/ChannelType.ts, front-end/src/Props/ChatInfoProps.tsx, front-end/src/Props/ChatUserProps.ts, front-end/src/UI/Molecules/DirectMessageToastContent/index.tsx, front-end/src/UI/Pages/Main/index.tsx, front-end/src/UI/Templates/ChatMessage/index.tsx, front-end/src/UI/Templates/DirectMessage/index.tsx, front-end/src/index.tsx
- 'PRIVATE' | 'PUBLIC' | 'PROTECT' 같은 코드를 enum으로 모두 리팩토링
- <img width="540" alt="image" src="https://user-images.githubusercontent.com/40755203/185851514-f2af9eb8-5b85-45a1-b46c-a044da0d8fed.png">
- 게임 및 해당 인원과 DM중이 아닐 경우를 제외하고, 토스트를 통해서
DM알림이 오게 구현함.
=> DM시 토스트 알림 & Refactor channel enums

back-end/src/chat/chat.service.ts, back-end/src/dm/dm.service.ts, back-end/src/socket/game/dto/req/game.invite.dto.ts, back-end/src/socket/game/socket-game.service.ts, back-end/src/socket/socket-state.service.ts, back-end/src/socket/socket-storage.service.ts, back-end/src/socket/socket.gateway.ts, back-end/src/socket/socket.module.ts, back-end/src/socket/socket.service.ts
- 게이트웨이의 서비스 로직 서비스로 이전
- dependency 해결하기 위해 storage service 생성
- game.invite dto 생성
=> TL42-250-be-socket-gateway-리펙토링-작업

front-end/src/Props/ChatEvent.ts, front-end/src/UI/Molecules/KickMenu/index.tsx, front-end/src/UI/Templates/ChatMessage/index.tsx, front-end/src/UI/Templates/UserContextMenu/index.tsx, front-end/src/WebSockets/dto/constants/chat.user.update.enum.ts, front-end/src/WebSockets/dto/res/chat.update.user.notify.dto.ts
- ChatUpdateUserNotifyProps, enum ChatUserUpdate 생성
- kickmenu 만들고 컨텍스트 메뉴에서 kickmenu 추가
- chatmessage에서 소켓연결해서 실험해보고 난후 코드 주석처리
=> [TL42-214] feat: 추방하기 기능구현

back-end/src/game/game.service.ts, back-end/src/socket/game/socket-game.service.ts
- 전적 기록 AND 연산으로 인해 조회가 안되는 상황 OR 연산으로 해결
- 래더 게임만 랭크 점수 반영으로 수정
=> TL42-253-be-game-전적-기록-못-불러오는-이슈

back-end/src/chat/chat.module.ts, back-end/src/chat/chat.service.ts, back-end/src/socket/socket.module.ts, back-end/src/socket/socket.service.ts, front-end/src/Hooks/useChatState.tsx, front-end/src/Hooks/useDirectMessageNotify.tsx, front-end/src/Hooks/useMessage.ts, front-end/src/Queries/Channels/Join.ts, front-end/src/Queries/QueryBuilder.ts, front-end/src/UI/Molecules/ChannelElement/index.tsx, front-end/src/UI/Molecules/ProtectedChannelElement/index.tsx, front-end/src/UI/Organisms/ChatHeader/index.tsx, front-end/src/UI/Organisms/ChatMessageContent/index.tsx, front-end/src/UI/Pages/Main/index.tsx, front-end/src/UI/Templates/ChangePasswordChannel/index.tsx, front-end/src/UI/Templates/ChatMessage/index.tsx, front-end/src/UI/Templates/CreateChannel/index.tsx, front-end/src/UI/Templates/DirectMessage/index.tsx
- 간헐적으로 채팅 join POST요청이 서버로 안가는데, 원인을 발견하지
못하였음...
=> [TL42-252] fix: 채팅 재입장 관련 이슈 수정 

front-end/src/UI/Pages/OTPRevise/index.tsx
axios로 post 하는 부분에 의존성 추가해서 문제 해결
=> [TL42-254] fix: OTP 문제 해결

front-end/src/UI/Molecules/BanMenu/index.tsx, front-end/src/UI/Organisms/ChatMessageContent/index.tsx, front-end/src/UI/Organisms/UserGameInfo/index.tsx, front-end/src/UI/Templates/UserContextMenu/index.tsx
- 영구추방시 api 요청
- chatMessageContent 쓸모없는 코드 삭제
- 승률 이름 -> 랭크승률로 수정
- 차단 관련한 문제 주석으로 달아놓음
=> [TL42-248] feat: BanMenu 기능 추가

back-end/src/chat/chat.controller.ts, back-end/src/chat/chat.service.ts, back-end/src/chat/chat.user.repository.ts, back-end/src/chat/dto/update.role.dto.ts
- 관리자 위임 인자 oldAdmin, newAdmin 에서 위임할 유저 nickname으로
변경
- 관리자 위임 해제 API  추가
=> TL42-256-be-chat-관리자-위임-해제

back-end/src/friend/dto/friend.block.list.dto.ts, back-end/src/friend/friend.controller.ts, back-end/src/friend/friend.repository.ts, back-end/src/friend/friend.service.ts
=> [TL42-257] feat: 차단 리스트

back-end/src/chat/chat.service.ts, back-end/src/socket/chat/dto/chat.update.user.notify.dto.ts, back-end/src/socket/socket.service.ts
=> [TL42-260] chore: ChatUpdateUserNotify dto 수정

front-end/src/Hooks/useChatNotify.ts, front-end/src/Hooks/useMessage.ts, front-end/src/UI/Molecules/MuteMenu/index.tsx, front-end/src/UI/Organisms/ChatMessageContent/index.tsx, front-end/src/UI/Templates/ChatMessage/index.tsx, front-end/src/UI/Templates/UserContextMenu/index.tsx, front-end/src/WebSockets/dto/res/chat.update.user.notify.dto.ts
- 음소거 기능 추가
- useMessage에서 updateRoomMember 디펜던시 수정
- ChatUpdateUserNotifyProps 에 프로퍼티 id (userId) 추가
=> [TL42-215] feat: 음소거 기능

front-end/src/Hooks/useChatNotify.ts, front-end/src/UI/Molecules/SpectateMenu/index.tsx
- 오너 바뀔 시 변경사항 updateRoomMember 이용해서 쏴주기.
- CHAT_UPDATE_USER_NOTIFY 소켓이벤트 switch 이용해서 refactor
=> [TL42-261] feat & refactor: 오너바뀔 시 아이콘 변경

back-end/src/chat/chat.controller.ts, back-end/src/chat/chat.service.ts
- 오너와 어드민 권한 정리
- api 응답값 정리 API 문서 참조
=> TL42-262-be-chat-추방-영구-추방-음소거-설정-및-해제-권한-정리

back-end/src/friend/dto/friend.block.list.dto.ts, back-end/src/friend/friend.repository.ts, front-end/src/Hooks/useChatNotify.ts, front-end/src/Props/BlocksProps.ts, front-end/src/UI/Templates/DirectMessage/index.tsx, front-end/src/UI/Templates/UserContextMenu/index.tsx
- DM 부분 upsert로 생기는 Warning 때문에 처음은 insert로 바꿈
- DM과 Chat 모두 차단한 사용자로부터 채팅 수신하지 않음.
- 백엔드 코드는 blocklist 받을 때 닉네임도 받을 수 있도록 수정
- DM에서 자기자신 콘텍스트 메뉴 수정
=> Tl42 246 fe chat dm 차단기능 구현

front-end/src/UI/Organisms/ChatMessageContent/index.tsx, front-end/src/UI/Templates/DirectMessage/index.tsx
- 채팅방에서 빈칸인 상태로 엔터를 누르면 애로우 백이 계속 동글동글
돌아가던 문제 해결
=> [TL42-XX] fix : 채팅 빈칸 입력시 문제 수정

front-end/src/Hooks/useSocket.tsx, front-end/src/UI/Atoms/Logo/index.tsx, front-end/src/UI/Molecules/LogoutMenu/index.tsx, front-end/src/UI/Pages/InitialSetup/index.tsx
- [로그아웃 관련 문제 수정](https://github.com/42TransLand/ft_transcendence/commit/3088e2b25b094f668e63746e32f1bf975fe0d673)
- [fix: 라우팅 경로에 상관없이 로고 로딩](https://github.com/42TransLand/ft_transcendence/commit/aca3cbfc1c7cdba1410e38b9b060bdfa426bd48a)
=> 로그아웃 문제 수정 및 로고 경로 수정
